global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'edge-nodes'
    static_configs:
      - targets: ['edge-node:8080']
    metrics_path: '/metrics'
    scheme: http

  - job_name: 'swarm-metrics'
    static_configs:
      - targets: ['edge-node:8080']
    metrics_path: '/swarm/metrics'
    scheme: http

  - job_name: 'solana-metrics'
    static_configs:
      - targets: ['edge-node:8080']
    metrics_path: '/blockchain/metrics'
    scheme: http
